#pragma once

#include "../FragmentTypes.hpp"
#include "../vampire/VampireRunner.hpp"
#include <string>
#include <vector>



//  printHeader
//  Prints a summary of the generation session
void printHeader(const std::string&           fragment,
                 const GenConfig&             cfg,
                 int                          count,
                 unsigned                     seed,
                 const std::vector<PredInfo>& vocab,
                 bool                         verify,
                 const std::string&           vampirePath,
                 int                          vampireTimeout);


//  printFormula
//  Parameters:
//    idx            - Index of the formula within the current session
//    cfg            - Configuration settings (used for mode and output) //check FragmentTypes.hpp
//    formulaStr     - Serialized formula generated by generateFormatted()
//    verify         - If true, executes the Vampire verification prover
//    runner         - Pointer to the VampireRunner instance
//    vampireTimeout - Timeout duration for Vampire, in seconds

void printFormula(int                  idx,
                  const GenConfig&     cfg,
                  const std::string&   formulaStr,
                  bool                 verify,
                  const VampireRunner* runner,
                  int                  vampireTimeout);